    util.h.xy.cy.f \u02bb()
    {
        java.lang.Throwable $r3;
        util.h.xy.cy.mh r0;
        java.lang.NullPointerException r4;
        java.util.Vector $r2;
        int $i0, $i1;
        util.h.xy.cy.rx $r1;
        boolean $z0;

        r0 := @this: util.h.xy.cy.mh;

        $r1 = new util.h.xy.cy.rx;

        specialinvoke $r1.<util.h.xy.cy.rx: void <init>()>();

        $r2 = r0.<util.h.xy.cy.mh: java.util.Vector \u02ca>;

        $r1.<util.h.xy.cy.mh: java.util.Vector \u02ca> = $r2;

        $i0 = <util.h.xy.cy.mh: int \u02bd>;

        $i0 = $i0 + 25;

        $i1 = $i0 % 128;

        <util.h.xy.cy.mh: int \u02bb> = $i1;

        $i0 = $i0 % 2;

        if $i0 != 0 goto label1;

        $z0 = 0;

        goto label2;

     label1:
        $z0 = 1;

     label2:
        if $z0 == 1 goto label5;

     label3:
        r4 = new java.lang.NullPointerException;

        specialinvoke r4.<java.lang.NullPointerException: void <init>(java.lang.String)>("This statement would have triggered an Exception: specialinvoke $u1#9.<java.lang.Object: int hashCode()>()");

        throw r4;

     label4:
        $r3 := @caughtexception;

        throw $r3;

     label5:
        return $r1;

        catch java.lang.Throwable from label3 to label4 with label4;
    }
