    public final util.h.xy.cy.f \u02bd() throws java.io.IOException
    {
        util.h.xy.cy.rn $r1;
        java.lang.Throwable $r4;
        util.h.xy.cy.d $r5;
        util.h.xy.cy.rg $r2;
        util.h.xy.cy.p r0;
        util.h.xy.cy.rc $r3;
        int $i0, $i1;
        java.lang.String $r6;

        r0 := @this: util.h.xy.cy.p;

        $r1 = new util.h.xy.cy.rn;

        $r2 = r0.<util.h.xy.cy.p: util.h.xy.cy.rg \u02ca>;

     label1:
        $r3 = virtualinvoke $r2.<util.h.xy.cy.rg: util.h.xy.cy.rc \u02ce()>();

        specialinvoke $r1.<util.h.xy.cy.rn: void <init>(util.h.xy.cy.rc)>($r3);

     label2:
        $i0 = <util.h.xy.cy.p: int \u02bd>;

        $i0 = $i0 + 101;

        $i1 = $i0 % 128;

        <util.h.xy.cy.p: int \u02bc> = $i1;

        return $r1;

     label3:
        $r4 := @caughtexception;

        $r5 = new util.h.xy.cy.d;

        $r6 = virtualinvoke $r4.<java.lang.Throwable: java.lang.String getMessage()>();

        specialinvoke $r5.<util.h.xy.cy.d: void <init>(java.lang.String,java.lang.Throwable)>($r6, $r4);

        throw $r5;

        catch java.lang.IllegalArgumentException from label1 to label2 with label3;
    }
