    public final util.h.xy.ct.mf \u02bb()
    {
        java.lang.Throwable $r2, $r3;
        util.h.xy.ct.rf $r4;
        util.h.xy.ct.n r0;
        util.h.xy.ct.mf $r1;
        java.lang.NullPointerException r6;
        int $i0, $i1;
        java.lang.String $r5;
        boolean $z0;

        r0 := @this: util.h.xy.ct.n;

        $i0 = <util.h.xy.ct.n: int \u02ce>;

        $i0 = $i0 + 17;

        $i0 = $i0 % 128;

        <util.h.xy.ct.n: int \u02cb> = $i0;

     label1:
        $r1 = virtualinvoke r0.<util.h.xy.ct.n: util.h.xy.ct.mf \u037a()>();

     label2:
        $i0 = <util.h.xy.ct.n: int \u02ce>;

        $i1 = $i0 | 13;

        $i1 = $i1 << 1;

        $i0 = $i0 ^ 13;

        $i0 = $i1 - $i0;

        $i1 = $i0 % 128;

        <util.h.xy.ct.n: int \u02cb> = $i1;

        $i0 = $i0 % 2;

        if $i0 == 0 goto label3;

        $z0 = 0;

        goto label4;

     label3:
        $z0 = 1;

     label4:
        if $z0 == 1 goto label8;

     label5:
        r6 = new java.lang.NullPointerException;

        specialinvoke r6.<java.lang.NullPointerException: void <init>(java.lang.String)>("Invalid array reference replaced by Soot");

        throw r6;

     label6:
        $r2 := @caughtexception;

        throw $r2;

     label7:
        $r3 := @caughtexception;

        $r4 = new util.h.xy.ct.rf;

        $r5 = virtualinvoke $r3.<java.lang.Throwable: java.lang.String getMessage()>();

        specialinvoke $r4.<util.h.xy.ct.rf: void <init>(java.lang.String)>($r5);

        throw $r4;

     label8:
        return $r1;

        catch java.io.IOException from label1 to label2 with label7;
        catch java.lang.Throwable from label5 to label6 with label6;
    }
